name: Polaris
on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      SECURITY_GATE_FILTERS: '{ "severity": ["high", "medium"], "cwe": [ "319" ], "status": [ "new" ] }'

    steps:
      - uses: actions/checkout@v2

      - name: Synopsys Polaris Security Testing
        uses: jcroall/polaris-report-action@v0.1.0
        with:
          polaris-url: ${{ secrets.POLARIS_URL }}
          polaris-access-token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          security-gate-filters: ${{ env.SECURITY_GATE_FILTERS }}
          debug: true
          polaris-command: analyze -w
          github-token: ${{ secrets.GITHUB_TOKEN }}

