name: Polaris
on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:
  env:
    POLARIS_FILTERS: '{ "severity": ["High", "Medium"], "cwe": [ "319" ], "status": [ "New" ] }'

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Synopsys Polaris Security Testing
        uses: jcroall/polaris-report-action@v0.1.0
        with:
          polaris-url: ${{ secrets.POLARIS_URL }}
          polaris-access-token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          security-gate-filters: ${{ env.POLARIS_FILTERS }}
          debug: true
          polaris-command: analyze -w
          github-token: ${{ secrets.GITHUB_TOKEN }}
